services:
  - mongodb
before_script:
  - sleep 15
  - mongo trainapptest --eval 'db.trainapptest.user.insert({"email":"bpsource@gmail.com"});'
  - mongo trainapptest --eval 'db.trainapptest.usersession.insert({"sessionId":"12312321323232312"});'
  - mongo trainapptest --eval 'db.trainapptest.device.insert({"title":"a1"});'
language: scala
script: 
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION test
scala:
  - 2.11.1
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  email:
    - bpsource@gmail.com
